name: Build
on:
    push:
        branches: [ "**" ]
        paths:
            - "BeatSaberModManager/**"
            - "BSIPA-Linux/**"
            - ".github/workflows/main.yml"
    pull_request:
        branches: [ "**" ]
        paths:
            - "BeatSaberModManager/**"
            - "BSIPA-Linux/**"
            - ".github/workflows/main.yml"

jobs:
    build_linux:
        name: Build Linux 
        runs-on: ubuntu-latest
        env:
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Setup .NET SDK
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: "8.0.x"

            -   name: Build Self Contained
                run: dotnet publish ./BeatSaberModManager/BeatSaberModManager.csproj -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: BeatSaberModManager-linux-x64-self-contained
                    path: BeatSaberModManager/bin/Release/linux-x64/publish/BeatSaberModManager

            -   name: Build Framework Dependent
                run: dotnet publish ./BeatSaberModManager/BeatSaberModManager.csproj -c Release -r linux-x64 --no-self-contained -p:PublishSingleFile=true
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: BeatSaberModManager-linux-x64-framework-dependent
                    path: BeatSaberModManager/bin/Release/linux-x64/publish/BeatSaberModManager
    
    build_windows:
        name: Build Windows
        runs-on: windows-latest
        env:
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Setup .NET SDK
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: "8.0.x"

            -   name: Build Self Contained
                run: dotnet publish ./BeatSaberModManager/BeatSaberModManager.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: BeatSaberModManager-win-x64-self-contained
                    path: BeatSaberModManager/bin/Release/win-x64/publish/BeatSaberModManager.exe

            -   name: Build Framework Dependent
                run: dotnet publish ./BeatSaberModManager/BeatSaberModManager.csproj -c Release -r win-x64 --no-self-contained -p:PublishSingleFile=true
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: BeatSaberModManager-win-x64-framework-dependent
                    path: BeatSaberModManager/bin/Release/win-x64/publish/BeatSaberModManager.exe
